# Generated by Django 6.0.3 on 2026-03-24 13:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_salesbill_customer_gstin_salesbill_is_b2b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
