# Generated by Django 6.0.3 on 2026-03-28 14:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pharmacy_state'),
        ('billing', '0003_salesitem_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesbill',
            name='customer_gstin',
        ),
        migrations.RemoveField(
            model_name='salesbill',
            name='is_b2b',
        ),
        migrations.AddField(
            model_name='salesbill',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='UNPAID', max_length=10),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='free_quantity',
            field=models.IntegerField(default=0, help_text='Free tablets given (Buy X Get Y). Deducts from physical stock, but does NOT affect line_total or taxes.'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='quantity',
            field=models.IntegerField(help_text='Tablets deducted from stock AND charged to the customer.'),
        ),
        migrations.CreateModel(
            name='CustomerParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_type', models.CharField(choices=[('B2B', 'Wholesale Clinic/Pharma'), ('B2C', 'Retail Patient')], default='B2C', max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.pharmacy')),
            ],
        ),
        migrations.AddField(
            model_name='salesbill',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Strict link to B2B/B2C Ledger. Leave null for guest walk-ins.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='billing.customerparty'),
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI/NEFT'), ('CHEQUE', 'Cheque')], default='CASH', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Cheque No. or UTR', max_length=100, null=True)),
                ('receipt_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('amount_allocated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='billing.customerparty')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.pharmacy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.salesbill')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.pharmacy')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.paymentreceipt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='customerparty',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'phone'), name='unique_customer_phone_per_pharmacy'),
        ),
    ]
