# Generated by Django 6.0.3 on 2026-03-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_fix_add_missing_customer_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbill',
            name='buyer_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
