# Generated by Django 6.0.3 on 2026-04-09 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_item4_drug_schedule_buyer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbill',
            name='split_payments',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='salesbill',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CREDIT', 'Credit'), ('SPLIT', 'Split')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='sales_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='billing.salesbill'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='sales_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='billing.salesitem'),
        ),
    ]
