# Generated by Django 6.0.3 on 2026-04-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_salesbill_split_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbill',
            name='prescriber_name',
            field=models.CharField(blank=True, help_text='Name of prescribing doctor — required for Sch H/H1/X/NARCOTIC', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='prescriber_reg_no',
            field=models.CharField(blank=True, help_text='Doctor/Clinic/Hospital registration number — required for Sch H1/X/NARCOTIC', max_length=100, null=True),
        ),
    ]
