# Generated by Django 6.0.3 on 2026-04-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_add_prescriber_fields_to_salesbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerparty',
            name='drug_license_no',
            field=models.CharField(blank=True, help_text='Drug License No. (Form 20/20B/21/21B) — mandatory for B2B pharmacy/distributor buyers under Drugs & Cosmetics Act, 1940', max_length=50, null=True),
        ),
    ]
