# Generated by Django 6.0.3 on 2026-04-09 16:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_add_drug_license_no_to_customerparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbill',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='place_of_supply',
            field=models.CharField(blank=True, help_text="2-digit GST state code e.g. '27' for Maharashtra", max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='credit_note_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
