# Generated by Django 6.0.3 on 2026-03-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
