# Generated by Django 6.0.3 on 2026-03-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='state',
            field=models.CharField(default='Maharashtra', help_text='Used for CGST/SGST vs IGST calculation', max_length=100),
        ),
    ]
