# Generated by Django 6.0.3 on 2026-04-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pharmacy_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='address',
            field=models.TextField(blank=True, help_text='Full address — appears on GST invoices', null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='invoice_counter',
            field=models.IntegerField(default=0),
        ),
    ]
