# Generated by Django 6.0.3 on 2026-03-16 23:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pharmacy_settings'),
        ('inventory', '0002_medicinemaster_default_gst_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shelf_number', models.IntegerField(help_text='Shelf number within the block, 1-indexed')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.pharmacy')),
            ],
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.shelflocation'),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('delta', models.IntegerField(help_text='new_quantity - old_quantity. Negative = shrinkage.')),
                ('adjusted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='Weekly Sync', max_length=255)),
                ('source', models.CharField(choices=[('SYNC', 'Weekly Sync'), ('MANUAL', 'Manual Adjustment')], default='SYNC', max_length=20)),
                ('adjusted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('inventory_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.inventorybatch')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.pharmacy')),
                ('shelf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.shelflocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_letter', models.CharField(help_text="Single uppercase letter identifying this block, e.g. 'A', 'B', 'C'", max_length=1)),
                ('shelf_count', models.IntegerField(help_text='Number of shelves in this block')),
                ('label', models.CharField(blank=True, help_text="Optional descriptive label, e.g. 'Refrigerated', 'Antibiotics'", max_length=100, null=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.pharmacy')),
            ],
        ),
        migrations.AddField(
            model_name='shelflocation',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='inventory.warehouseblock'),
        ),
        migrations.AddConstraint(
            model_name='warehouseblock',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'block_letter'), name='unique_block_letter_per_pharmacy'),
        ),
        migrations.AddConstraint(
            model_name='shelflocation',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'block', 'shelf_number'), name='unique_shelf_per_block_per_pharmacy'),
        ),
    ]
