# Generated by Django 6.0.3 on 2026-03-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_shelflocation_inventorybatch_shelf_stockadjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
