# Generated by Django 6.0.3 on 2026-03-24 11:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_customuser_organization_and_more'),
        ('inventory', '0004_purchasereturn_mrp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_deadline', models.DateField(help_text='Last date supplier accepts this return')),
                ('alert_date', models.DateField(help_text='Date this alert was surfaced to the owner')),
                ('gst_quarter_deadline', models.DateField(blank=True, help_text='GST filing deadline for the quarter this return falls in', null=True)),
                ('gst_credit_at_risk', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated GST input credit lost if return is missed', max_digits=10)),
                ('gst_warning', models.BooleanField(default=False)),
                ('estimated_sell_quantity', models.IntegerField(default=0, help_text='Predicted units sellable before expiry based on velocity')),
                ('recommendation', models.CharField(choices=[('SELL', 'Sell before expiry'), ('RETURN', 'Return to supplier'), ('PARTIAL', 'Sell some, return rest')], default='RETURN', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Decision'), ('RETURN', 'Marked for Return'), ('SELL', 'Decision: Sell Before Expiry'), ('IGNORED', 'Ignored')], default='PENDING', max_length=20)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_alerts', to='inventory.inventorybatch')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.pharmacy')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_alerts', to='inventory.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierReturnPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_window_days', models.IntegerField(default=90, help_text='Days before expiry date by which returns must be initiated')),
                ('gst_credit_eligible', models.BooleanField(default=True, help_text='Does this supplier issue GST credit notes on returns?')),
                ('advance_notice_days', models.IntegerField(default=14, help_text='Alert fires this many days before the return window closes')),
                ('notes', models.TextField(blank=True, null=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.pharmacy')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_policy', to='inventory.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
