# Generated by Django 6.0.3 on 2026-03-24 13:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_purchasebill_total_cgst_purchasebill_total_igst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
