# Generated by Django 6.0.3 on 2026-03-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pharmacy_state'),
        ('inventory', '0007_purchaseitem_discount_percentage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorybatch',
            name='unique_batch_mrp_per_pharmacy',
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'medicine', 'batch_number', 'mrp', 'gst_percentage'), name='unique_batch_mrp_per_pharmacy'),
        ),
    ]
