# Generated by Django 6.0.3 on 2026-03-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pharmacy_state'),
        ('inventory', '0008_remove_inventorybatch_unique_batch_mrp_per_pharmacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemaster',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicinemaster',
            name='salt_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='medicinemaster',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('pharmacy', 'barcode'), name='unique_barcode_per_pharmacy'),
        ),
    ]
