# Generated by Django 6.0.3 on 2026-03-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_medicinemaster_barcode_medicinemaster_salt_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemaster',
            name='drug_schedule',
            field=models.CharField(choices=[('GENERAL', 'General'), ('H', 'Schedule H'), ('H1', 'Schedule H1'), ('X', 'Schedule X'), ('NARCOTIC', 'Narcotic')], default='GENERAL', max_length=20),
        ),
    ]
