# Generated by Django 6.0.3 on 2026-04-09 09:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_item4_drug_schedule_buyer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='adjustment_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='purchase_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='tax_reversal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
