# Generated by Django 6.0.3 on 2026-04-09 16:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stockadjustment_adjustment_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemaster',
            name='uqc',
            field=models.CharField(choices=[('TAB', 'Tablets'), ('CAP', 'Capsules'), ('BOT', 'Bottles'), ('AMP', 'Ampoules'), ('VIA', 'Vials'), ('TUB', 'Tubes'), ('SYR', 'Syringes'), ('PKT', 'Packets'), ('BOX', 'Box/Carton'), ('GM', 'Grams'), ('KG', 'Kilograms'), ('ML', 'Milliliters'), ('LTR', 'Liters'), ('PAC', 'Packs'), ('NOS', 'Numbers'), ('OTH', 'Others')], default='TAB', help_text='Unit Quantity Code for GSTR-1 HSN Summary (Table 12)', max_length=5),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='has_credit_note',
            field=models.BooleanField(default=False, help_text='True if supplier issued a formal GST credit note'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='supplier_credit_note_no',
            field=models.CharField(blank=True, help_text='Credit note number issued by the supplier', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='cgst_reversal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='igst_reversal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='sgst_reversal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
